import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Or your Geist fonts
import "./globals.css";

const inter = Inter({ subsets: ["latin"] }); // Or your Geist font initialization

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // --- THE FIX: Apply the font class to the html or body tag ---
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}